-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 09:32:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyBD` DEFAULT CHARACTER SET utf8 ;
USE `MyBD` ;

-- -----------------------------------------------------
-- Table `MyBD`.`Check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Check` (
  `Check_ID` INT NOT NULL,
  `Check_total_price` INT NOT NULL,
  `Check_data` DATETIME NOT NULL,
  PRIMARY KEY (`Check_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Client` (
  `Client_ID` INT NOT NULL,
  `Client_name` MEDIUMTEXT NOT NULL,
  `Client_telephone` INT NOT NULL,
  `Client_address` LONGTEXT NOT NULL,
  PRIMARY KEY (`Client_ID`),
  UNIQUE INDEX `Client_ID_UNIQUE` (`Client_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Transport_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Transport_service` (
  `Transport_service_ID` INT NOT NULL,
  `Transport_service_completed_work` LONGTEXT NOT NULL,
  `Transport_service_replaced_spare_part` LONGTEXT NULL,
  `Transport_service_recommendation` LONGTEXT NULL,
  `Transport_service_last_date` DATETIME NOT NULL,
  `Transport_service_next_data` DATETIME NOT NULL,
  PRIMARY KEY (`Transport_service_ID`),
  UNIQUE INDEX `Transport_service_ID_UNIQUE` (`Transport_service_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Vehicle` (
  `Vehicle_ID` INT NOT NULL,
  `Vehicle_registatin_number` TINYTEXT NOT NULL,
  `Vehicle_brand` TINYTEXT NOT NULL,
  `Vehicle_color` TINYTEXT NOT NULL,
  `Vehicle_model` TINYTEXT NOT NULL,
  `Vehicle_year_of_issue` TINYTEXT NOT NULL,
  `Transport_service_Transport_service_ID` INT NOT NULL,
  PRIMARY KEY (`Vehicle_ID`, `Transport_service_Transport_service_ID`),
  UNIQUE INDEX `Vehicle_registatin_number_UNIQUE` (`Vehicle_registatin_number` ASC) VISIBLE,
  UNIQUE INDEX `Vehicle_ID_UNIQUE` (`Vehicle_ID` ASC) VISIBLE,
  INDEX `fk_Vehicle_Transport_service1_idx` (`Transport_service_Transport_service_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicle_Transport_service1`
    FOREIGN KEY (`Transport_service_Transport_service_ID`)
    REFERENCES `MyBD`.`Transport_service` (`Transport_service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Diagnostic_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Diagnostic_card` (
  `Diagnostic_card_ID` INT NOT NULL,
  `Diagnostic_card_quanity_spare_part` INT NULL,
  `Master_Master_ID` INT NOT NULL,
  PRIMARY KEY (`Diagnostic_card_ID`, `Master_Master_ID`),
  UNIQUE INDEX `Diagnostic_card_ID_UNIQUE` (`Diagnostic_card_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Master` (
  `Master_ID` INT NOT NULL,
  `Master_name` MEDIUMTEXT NOT NULL,
  `Master_telephone` INT NOT NULL,
  PRIMARY KEY (`Master_ID`),
  UNIQUE INDEX `Master_ID_UNIQUE` (`Master_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Client_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Client_record` (
  `Client_record_ID` INT NOT NULL,
  `Client_record_data` DATETIME NOT NULL,
  `Client_completion_date` DATETIME NOT NULL,
  `Client_Client_ID` INT NOT NULL,
  `Vehicle_Vehicle_ID` INT NOT NULL,
  `Vehicle_Transport_service_Transport_service_ID` INT NOT NULL,
  `Check_Check_ID` INT NOT NULL,
  `Diagnostic_card_Diagnostic_card_ID` INT NOT NULL,
  `Master_Master_ID` INT NOT NULL,
  PRIMARY KEY (`Client_record_ID`, `Client_Client_ID`, `Vehicle_Vehicle_ID`, `Vehicle_Transport_service_Transport_service_ID`, `Check_Check_ID`, `Diagnostic_card_Diagnostic_card_ID`, `Master_Master_ID`),
  INDEX `fk_Client_record_Client1_idx` (`Client_Client_ID` ASC) VISIBLE,
  INDEX `fk_Client_record_Vehicle1_idx` (`Vehicle_Vehicle_ID` ASC, `Vehicle_Transport_service_Transport_service_ID` ASC) VISIBLE,
  INDEX `fk_Client_record_Check1_idx` (`Check_Check_ID` ASC) VISIBLE,
  INDEX `fk_Client_record_Diagnostic_card1_idx` (`Diagnostic_card_Diagnostic_card_ID` ASC) VISIBLE,
  UNIQUE INDEX `Client_record_ID_UNIQUE` (`Client_record_ID` ASC) VISIBLE,
  INDEX `fk_Client_record_Master1_idx` (`Master_Master_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Client_record_Client1`
    FOREIGN KEY (`Client_Client_ID`)
    REFERENCES `MyBD`.`Client` (`Client_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_record_Vehicle1`
    FOREIGN KEY (`Vehicle_Vehicle_ID` , `Vehicle_Transport_service_Transport_service_ID`)
    REFERENCES `MyBD`.`Vehicle` (`Vehicle_ID` , `Transport_service_Transport_service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_record_Check1`
    FOREIGN KEY (`Check_Check_ID`)
    REFERENCES `MyBD`.`Check` (`Check_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_record_Diagnostic_card1`
    FOREIGN KEY (`Diagnostic_card_Diagnostic_card_ID`)
    REFERENCES `MyBD`.`Diagnostic_card` (`Diagnostic_card_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_record_Master1`
    FOREIGN KEY (`Master_Master_ID`)
    REFERENCES `MyBD`.`Master` (`Master_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Works` (
  `Works_ID` INT NOT NULL,
  `Works_name` MEDIUMTEXT NOT NULL,
  `Works_price` INT NOT NULL,
  PRIMARY KEY (`Works_ID`),
  UNIQUE INDEX `Works_ID_UNIQUE` (`Works_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Faults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Faults` (
  `Faults_ID` INT NOT NULL,
  `Faults_name` MEDIUMTEXT NOT NULL,
  `Faults_wall_of_danger` INT NOT NULL,
  `Works_Works_ID` INT NOT NULL,
  `Diagnostic_card_Diagnostic_card_ID` INT NOT NULL,
  `Diagnostic_card_Master_Master_ID` INT NOT NULL,
  PRIMARY KEY (`Faults_ID`, `Works_Works_ID`, `Diagnostic_card_Diagnostic_card_ID`, `Diagnostic_card_Master_Master_ID`),
  UNIQUE INDEX `Faults_ID_UNIQUE` (`Faults_ID` ASC) VISIBLE,
  INDEX `fk_Faults_Works1_idx` (`Works_Works_ID` ASC) VISIBLE,
  INDEX `fk_Faults_Diagnostic_card1_idx` (`Diagnostic_card_Diagnostic_card_ID` ASC, `Diagnostic_card_Master_Master_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Faults_Works1`
    FOREIGN KEY (`Works_Works_ID`)
    REFERENCES `MyBD`.`Works` (`Works_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faults_Diagnostic_card1`
    FOREIGN KEY (`Diagnostic_card_Diagnostic_card_ID` , `Diagnostic_card_Master_Master_ID`)
    REFERENCES `MyBD`.`Diagnostic_card` (`Diagnostic_card_ID` , `Master_Master_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Spare_part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Spare_part` (
  `Spare_part_ID` INT NOT NULL,
  `Spare_part_name` MEDIUMTEXT NOT NULL,
  `Spare_part_price` DOUBLE NOT NULL,
  PRIMARY KEY (`Spare_part_ID`),
  UNIQUE INDEX `Spare_part_ID_UNIQUE` (`Spare_part_ID` ASC) VISIBLE,
  UNIQUE INDEX `Spare_part_name_UNIQUE` (`Spare_part_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBD`.`Ordering_Spare_Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBD`.`Ordering_Spare_Parts` (
  `Ordering_Spare_Parts_ID` INT NOT NULL,
  `Ordering_Spare_Parts_quantity` INT NULL,
  `Ordering_Spare_Parts_total_price` INT NULL,
  `Spare_part_Spare_part_ID` INT NOT NULL,
  `Diagnostic_card_Diagnostic_card_ID` INT NOT NULL,
  `Diagnostic_card_Master_Master_ID` INT NOT NULL,
  INDEX `fk_Ordering_Spare_Parts_Spare_part1_idx` (`Spare_part_Spare_part_ID` ASC) VISIBLE,
  PRIMARY KEY (`Ordering_Spare_Parts_ID`),
  UNIQUE INDEX `Ordering_Spare_Parts_ID_UNIQUE` (`Ordering_Spare_Parts_ID` ASC) VISIBLE,
  INDEX `fk_Ordering_Spare_Parts_Diagnostic_card1_idx` (`Diagnostic_card_Diagnostic_card_ID` ASC, `Diagnostic_card_Master_Master_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Ordering_Spare_Parts_Spare_part1`
    FOREIGN KEY (`Spare_part_Spare_part_ID`)
    REFERENCES `MyBD`.`Spare_part` (`Spare_part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordering_Spare_Parts_Diagnostic_card1`
    FOREIGN KEY (`Diagnostic_card_Diagnostic_card_ID` , `Diagnostic_card_Master_Master_ID`)
    REFERENCES `MyBD`.`Diagnostic_card` (`Diagnostic_card_ID` , `Master_Master_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
